spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 15MB
  application:
    name: investMe
  datasource:
    url: jdbc:postgresql://ec2-54-166-242-77.compute-1.amazonaws.com:5432/d8n52r1l9ecr89
    username: aaxnzognztjrls
    password: 9f9a1738ed089a99ebc6ffb56eae697798f630ea658a47369cdd3ab166057290
    testwhileIdle: true
    validationQuery: SELECT 1
    minIdle: 10
    maxIdle: 50
    initialSize: 10
    maxWait: 60000
    testOnBorrow: true
    hikari:
      maxLifetime: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: password
    sign: InvestMe Team
    location: United State
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9000

security:
  public:
    endpoint: /invest/me/api/api-docs/**,/invest/me/api/swagger-ui/**,/invest/me/api/authentication,/invest/me/api/students,/invest/me/api/investors,/invest/me/api/companies,/invest/me/api/totp,/invest/me/api/reset,/invest/me/api/contents/cgu,/invest/me/api/accounts/pdp
  jwt:
    secret: secret
    expiration:
      time: 2592000000

springdoc:
  swagger-ui:
    path: /invest/me/api/swagger-ui
  api-docs:
    path: /invest/me/api/api-docs
     
multipart:
  enabled: true
  
cloudinary:
  cloud_name: techiprimer
  api_key: 815176751335227
  api_secret: Lst0rp_kjYatr-fAfjMycRS5BwQ
      
        
app:
  firebase-configuration-file : 

    
              