spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 15MB
  application:
    name: InvestMe
  datasource:
    url: jdbc:postgresql://localhost:5432/investme_db
    username: investme
    password: PradeepInvestMeProject
    testwhileIdle: true
    validationQuery: SELECT 1
    minIdle: 10
    maxIdle: 50
    initialSize: 10
    maxWait: 60000
    testOnBorrow: true
    hikari:
      maxLifetime: 30000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${investme_email}
    password: ${investme_password}
    sign: InvestMe Team
    location: United State
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 443
  ssl:
    key-store: /etc/letsencrypt/live/nvstm.com/keystore.p12
    key-store-password: password
    keyStoreType: PKCS12

security:
  require-ssl: true
  public:
    endpoint: /invest/me/api/api-docs/**,/invest/me/api/swagger-ui/**,/invest/me/api/authentication,/invest/me/api/students,/invest/me/api/investors,/invest/me/api/companies,/invest/me/api/totp,/invest/me/api/reset,/invest/me/api/contents/cgu,/invest/me/api/accounts/pdp
  jwt:
    secret: JwtSecret@3343
    expiration:
      time: 2592000000

springdoc:
  swagger-ui:
    path: /invest/me/api/swagger-ui
  api-docs:
    path: /invest/me/api/api-docs
     
multipart:
  enabled: true
  
cloudinary:
  cloud_name: ${cloud_name}
  api_key: ${cloud_key}
  api_secret: ${cloud_secret}
      
        
app:
  firebase-configuration-file : school-project-investme-firebase-adminsdk-j5j12-b282a07030.json

    
              